In [1]:
import numpy as np

In [2]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [3]:
np.full(10,69)

array([69, 69, 69, 69, 69, 69, 69, 69, 69, 69])

In [4]:
a = np.array([1,2,3,4,5])

In [5]:
a[2]

np.int64(3)

In [6]:
a

array([1, 2, 3, 4, 5])

In [7]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [9]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [11]:
n=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [12]:
n[1,1]

np.int64(5)

In [22]:
np.random.randn(5,3)

array([[-1.57981063,  0.90206841, -0.07941154],
       [-0.49430138, -0.3323965 , -1.06654713],
       [-0.82723022, -0.97811375,  0.99636285],
       [-0.19790456, -0.03942106,  0.91347267],
       [ 0.20941815,  0.27182551, -1.2832335 ]])

In [14]:
n=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [15]:
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
n[:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
n[:,2]

array([3, 6, 9])

In [18]:
n[:,2]=[1,1,1]

In [19]:
n

array([[1, 2, 1],
       [4, 5, 1],
       [7, 8, 1]])

In [20]:
n[3]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [21]:
n[2]

array([7, 8, 1])

In [24]:
np.random.randint(low=0 , high=100 , size=(5,2))

array([[31, 43],
       [41, 62],
       [54, 24],
       [47, 28],
       [44, 71]], dtype=int32)